# Generated by Django 4.2.5 on 2023-09-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblogapp', '0004_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
